name: 'CFF Update Action'
description: 'Automatically updates CFF file'

branding:
  color: 'blue'

runs:
    using: "composite"
    steps:
        - name: Checkout repo
          uses: actions/checkout@v2
        - name: Install Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.x'
        - name: Update CFF 
          shell: bash
          run: >-
            python 
            $GITHUB_ACTION_PATH/update_cff.py 
            $GITHUB_REF_NAME
        - name: Commit results
          run: |
            git config --local user.name "$GITHUB_ACTOR"
            git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
            git add CITATION.cff
            git commit -m 'Update CITATION.cff' 
            git fetch
            git push origin 
